const CACHE_ENTRY_TTL_SECONDS = 600; // 10 minutes
const CACHE_LOGIN_ENTRY_KEY_PREFIX = 'LOGIN';

const LOGIN_RATE_LIMIT = 5;

module.exports = {
  CACHE_ENTRY_TTL_SECONDS,
  CACHE_LOGIN_ENTRY_KEY_PREFIX,
  LOGIN_RATE_LIMIT,
}
